name: Build, Deploy [Main]

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Deplay to github pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER:  ./
          CLEAN: true
